elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
    - "9300:9300"
  container_name: ssg-es
kibana:
  image: kibana:4.1.2
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  container_name: ssg-kibana
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logs:/logs
    - ./logstash/geoip:/etc/geoip
  links:
    - elasticsearch
  container_name: ssg-logstash
